### ISSUE TITLE
Google Login - AxiosError on New Account Login

### ISSUE THREAD

**Issue by guojiayupei** [cs5351-software-engineering/monorepo#3]
**Description**
When logging out of my Google account and trying to sign in with another Google account (one that has never been used for the application before), the login process successfully redirects to the dashboard page. However, an alert window pops up, indicating that there is an error. Upon pressing the alert, it states: "Unhandled runtime error: AxiosError: Request failed with status code 400."

The source of the error appears to be in the file app\dashboard\layout.tsx, which requires further investigation and resolution. If this issue is not addressed, users will be unable to access the application when attempting to log in with a new Google account.

**Steps to Reproduce**
1. Logout from the current Google account.
2. Sign in using a different Google account that has never been used with the app.
3. Successfully log in to the dashboard.
4. An alert window appears with the error message "AxiosError: Request failed with status code 400."
5. Upon clicking the alert, the error points to an issue in app\dashboard\layout.tsx.

**Expected behavior**
The login process should complete without errors, and users should be able to access the dashboard without encountering any issues, regardless of the Google account being used.

**Screenshots**
![image](https://github.com/user-attachments/assets/5fbb03f6-5650-400d-93e2-919045954de6)
![image](https://github.com/user-attachments/assets/1609f833-a654-4742-b635-6ea0f7396b6a)

**Actual Behavior**
An error message appears, and an unhandled runtime error occurs with the message "AxiosError: Request failed with status code 400." The source of the issue is located in app\dashboard\layout.tsx.

**Impact**
This bug prevents users from logging in with a new Google account and accessing the application.

**Possible Solution**
Investigate and fix the issue in app\dashboard\layout.tsx that causes the unhandled runtime error.

**Comment by CWKSC** [comment]
Seems this issue is related to the timing of init user id and request to server
